language: node_js
install: true
script: true
notifications:
  slack:
    rooms:
      secure: lUH55I14V3A4JKU4cuuiAzVFIgtBywlW0kRm2U4qvErZOCngH6PCaSJOtP/tyuxu6sXWlfs+4r9atXkrRZF5081Ld0lToYAXn4V5AU+H/i8Uy5hlqpSG+LLXqhOJD2piWrR+D7BGXpVzH13UQGEsTqvFmYNIwFDMSCebVDSCqvH/PGh9HQvAVyPQuJa6g1UFPgXU4YdhLRBPjqjc3fo+FdUGKEZCfFUMBXfnDiXtNiDIaOlrTXGJVimMWGlxu4lVIoj2ME4zENSDwElcqiC7xlpbvBNDnCDMawzv1J5i855kWI7mmU0LSb+VIkzrmMTIGpbQmV30ZrRrJWpceAtwtlNJyA4mtg348Gkl6GjZG8uB7/Wt4Uk0b+ps3skKIiP/b9V9uXhXbIo1dxT603yWBUlzgmBUqNKZwsyp8mrSg0YHWGv0tYVvFkRpn3eSRHJHgdyOk9C+mFEEcdAi1OOXk/VGOIlGXdl6pal5fA9OWSqV+1orET4SOXZzR3mLAtVA7m5xT5EikEEVuH2vs34rZTD7C8+rbHIMuOsP5N1udSUbUGbhAlmJqiMjLktaPBtTkHL1pc51DHSKan+mfudlKgeEeYjFPyFmY05hSf7rB00lZCKYfGzqRX9WX8B4St3rm6e5Y+d2Fi0QsVhbYGOrKh+eBitZ89rr3ZbxBJFiJrM=
