dist: xenial
language: python
deploy:
  provider: pypi
  user: ssabrii
  password:
    secure: AkRzFQEjH1BM1pN6r6XvQKVFj5dQAJ0lGvguOBsXmuPwVC4R6mybLrYlGeou2lkGUeTRbhdo/FoYLzhlDiA2yoJqBu1Z3EIiSggatwtaOPnw/iIlzCihdQIpB+oTfxt25VAY0HIhpq8a3V0gftNmy8KMZbOx+xlmypD1m3EthEIZvaRPquXO/D4O6f4XST2XX+hcPo96yFtRLD1Uk4VRG3qPqgPHUqBn6h6GfyZYcD0N+J1jZIlfXxpNc6IzXo5XPPTP4Xs1Amlh3ffK2UFiG604Osc/QY0Gst3lX6tdcpolfhAlerGCkAVhPQH3/E35zL0sOeNACYtXEBC+vUjk8HRAXkj32ou8wasXcHA3PXt9dvqKltAXK6v1TVqkfHuXU++orEfviSByqU5nl5f7vXiG8oiCe0ZkkGuKHHr2bLwvExtvtCqvSWTwy7JFkY9Ctuu7wwLB0+LM2lgCY5C5uFUJUZo85o07/JVIVkpqmxAWGcvPw/DCvPEDmhe17D5nYSJ/lzD+wrrmhEoEMWVu01tyH7HnyhYlvPT43QEtKYij49Fw/GgXdKzlSkqwJfyA5kLE3ci3rkmqK/X60G2tei0fx/7xs2GnoHWxMInBP4UJhEzEiXivGWwtDxJjAirNMVfPtaOOoqL8M3gyMGwg+xSL8/vJn4MvKQAVyw8BUNg=
  on:
    python: 3.6
env:
  global:
    secure: fzWLGx/ZEl8ab3fs7pLKJYqWdTcKYyiJZYQwgaWCoANvHktsyKNchUgikgjRX1CL2JpxInBcRADhOi1YbeOsd6uD2Yu6VBaZQCzse31QjsfFtH3DeLXmeeWWu7QGJ64K3NTwbYr/NF7MBQmhWO2lZ0XrXaV7ShjvfDS3jeB/pZ6cwM/5mE6j5FP1aAmQfzn76s/fo2q9qvHFxDIxn0QEmJF5yHdsJFPQB72/Y6uhxcUyMH4BZmW2KrAmW9wGvFj/kolmAD+lHNcx/Od6Mn+mTGvsUKjKr93jmxxv7thNW8lMK/SrOb8xgpTE/gr4TeyLF7C06Dm2feGJL1O06tYTI8tPjT9qm9ERZ3Iq1salzBXQl+UxTUs5nlR4S7Oyp9xv11wt8k7GHwp2V+FT2jrkKDyRbNfJRkMhv/pFmDZGdifMC8BZhbKBDVwFKbz5MfKgTuShggCRwjiv6oFZGKqYvIx2YJpSC5vzMf1D4KK/MoBMxqLFbaTIzg4f672ccV4c46EBYA10myHaq0WIczonH8RpdrXW7eU13NXVla02B6HbzucKJlsTS3wyqk2thG1xChMuPd2oAjMoM6vhFHjdC3nBVRjZYgrI5+fXy9ui1HQfSf8sA/FhtE26zRitFOlR/5+IYXOSQOHvRMm7VFYqERsAE+GVXFA9PMX2omCQlnY=
