language: generic
before_install:
- echo $BUILD_IOS_TRUE
- echo $TEST
install: true
script: true
env:
  global:
    secure: KVReNiFxdRMr4cf/GvnBoVQ2Zaihm1IEDXZmICqxn8YR3PJbinhPZIqzlVfdqj5wFJUL1xSP0xIHBTNWSbWRCdDopEy3ogcbQQN2sfJFOmwTU8tviuHFfI3IlSz4m5JuxK+LGBzzVKQXZsECeNrwhfLoWXj5T7zxSJk5YC6dzi/fa/fBwijrTjZEzkSAyoV8a3NMNVxZImiN7TgQkRB28JfWCtSy3p7WZqvs8G5i2O9Vfk2snDLguHqNHVWcXWZoxL7rqLUGMvQ0UQO+YFV0vcijtKqbQ8QvjU6B+50bz4A5T+u0J7NqbKIut5zGjGB0lZVCT9lVYEDO5uW5kBLnWHzJjUrn2gxdbHQrWXU+GBxXCYsgqEMWWMdedaUhhMB5zF6SpVas379CRuMLo72nLeFMQrvGtjmqnAkvb34Nz/b95nT+lWVNkYtGJNmiF95yFHcGkZHy/ZVjucysAxZgQ8PA6sK3x4Rg0U+F/5y3mnmOVyp6JGqsphh/YhjTbFqnVVMWW9UjoisdA0Z1TSh4l96UKm9Qqu+bAhiBFe5RX6QsqdVW1JILxM9v2R4deY0gUUsWXWDJVJtYavYlNwn+9RjPjdNBvMJ6nkwuvR3XQTsfaRnZvscdT431bs08vhCqbBLnM4k0HmVlKj6E+TfGWG/uHtq/kB0bi8vz0oFUINU=
