language: ruby
dist: trusty
addons:
  rethinkdb: '2.3.5'
script: printf "${marker}%b${ANSI_RESET}\n" "$text"
  
notifications:
  slack:
    rooms:
      secure: P+yNQAAEVWRTSzKPVMHWKM7smuMiT4qRFFjocxgJ52sy/hSK8qxAYdjnhBXwc3kn/0pBMsjik7RBOEkGq9CNHXDcGOkMheLO0n0rK4RJkhPgvFiuMLDPEmCb7kWmdEnQQU/UMMqvCXRV2fjOpfJ2B/qMqQESvQUoTuvDEHm/B/ep7lNMbWbhRWwRnw6Qif0NPWsNyt3EZZ2jLJaP7WQR1xJHmGbpHzyjJKgjMo/ak4eV518u3RPgi0Y2fKw+hEmBViOqxugCx+D6+SAhOObc78HqMv0AwrO+P1zC0u5Ob7uusaAZWe19V5/mW947hmKSW2AYGgqMUkaluwESNSG5Mfw+XqgcAH0puYgBstGl8X3G8beFbm6i/EMdcYNO1M5phFtFxnbSRPOPUY3YPcYTZQktbaC93oj+dQaezRKnbybpemNbLF2xb0jgWtbwLi+u1cqzWLHakATcTNGzrTUGek7Z8XlFpk68KJrL4EFu3E+qfAn9TgROW3crC0co1lwh+EFikTT91JY61xgZcF/6PPJF49kM1oCUFIQfP8LW8PVLzRPyLnOWDMnlOyyguSHHiIJXNr97wnqcmYvWfIgTAtAxOnqwyACRtks8bxHKlh+u2/Zv29s0h/BqeDyLXRZyJv0DHfH0fBNy1sZuLDyy4EowCEwI867vKVHFcXdRvpY=
  email:
    recipients:
      secure: TVDNApP0jn1nEQ5S50/GmuDRSKRs7cMxaBUCo8jaeKCtWvVNL7XQ6TFnjl1pjxybD9AmmSvikXExO8q1x9auHQtkoQJVP/7k1s5wYPkFBCIUQmHJXean1s+vhqrv83xgfvSpQqnZyQ9mDH0aTHSo1dHbY05NnfaVQijt9tFRyWJTTRBIW1FIy4vzIB3P+wZUZ/spQXZ3ObPQs9vjV8pJWSrtVf6kYcdYGXiiYn71qM3Dh2PpkRHGdWKrpbxhDgLVMt7K7i+mOSqS3RYTH3hWhaEDs5SeQA1xFAAHH6WZPhesl0Tzk6MIObal0nc/l/aqTcEx94Tme7w+7PsL2nhcgeW7gv34F+iy/bOWKglxgk0siqW+09cSC7lLUFszW3T8FtQeDwnTUbz/o0vOzD8TdHUoMOmbBuBYGFR8hI+K61Phif4XtTHYQD0QIlWswibu033IYlruV1c7+ZSEA7woK4IIcCxE3//tfkKoyAH+sX0EJfTlbzJyqQ2xauhfLL6Tkjx8CdVEg+Zb6s+RyM26WxHHjf07jTH2EqJi6z2YUzF8BzTc2lqUC1sUIAtvEyQsyrADqrTroO9vUYDYm5GuFh//MiwNYlyjfwLiGlZGCZPypjZYnESaTt+gXRpO0OEQXtCg0tqJ/Vp2zlTT9rDfHEsKMVJgcnEx+A2rSNOXOY4=
      on_success: always
