language: ruby

dist: xenial
branches:
  only:
    - master
before_install:
 - sudo apt-get update
 - sudo apt-get --no-install-recommends -qq install alien bc libaio1 unzip
 
install: true

script: true

# cache:
#   npm: true
#   directories:
#   - "$HOME/.npm"
