dist: trusty
language: ruby

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.4
  - 2.6.3
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
install: true
script: true
