language: python
dist: xenial

services:
  - postgresql
  
env:
  global:
  - PGPORT=5433

addons:
  postgresql: "11"
  apt:
   packages:
    - postgresql-11
    - postgresql-client-11
    
before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1

install: true
script:
  - psql -c 'create database travis_ci_test;' -U postgres


notifications:
  slack:
    rooms:
      secure: P+yNQAAEVWRTSzKPVMHWKM7smuMiT4qRFFjocxgJ52sy/hSK8qxAYdjnhBXwc3kn/0pBMsjik7RBOEkGq9CNHXDcGOkMheLO0n0rK4RJkhPgvFiuMLDPEmCb7kWmdEnQQU/UMMqvCXRV2fjOpfJ2B/qMqQESvQUoTuvDEHm/B/ep7lNMbWbhRWwRnw6Qif0NPWsNyt3EZZ2jLJaP7WQR1xJHmGbpHzyjJKgjMo/ak4eV518u3RPgi0Y2fKw+hEmBViOqxugCx+D6+SAhOObc78HqMv0AwrO+P1zC0u5Ob7uusaAZWe19V5/mW947hmKSW2AYGgqMUkaluwESNSG5Mfw+XqgcAH0puYgBstGl8X3G8beFbm6i/EMdcYNO1M5phFtFxnbSRPOPUY3YPcYTZQktbaC93oj+dQaezRKnbybpemNbLF2xb0jgWtbwLi+u1cqzWLHakATcTNGzrTUGek7Z8XlFpk68KJrL4EFu3E+qfAn9TgROW3crC0co1lwh+EFikTT91JY61xgZcF/6PPJF49kM1oCUFIQfP8LW8PVLzRPyLnOWDMnlOyyguSHHiIJXNr97wnqcmYvWfIgTAtAxOnqwyACRtks8bxHKlh+u2/Zv29s0h/BqeDyLXRZyJv0DHfH0fBNy1sZuLDyy4EowCEwI867vKVHFcXdRvpY=
