dist: xenial
language: ruby
stages:
 - name: test
   if: sender = 'ssabrii'
 - name: hello
   if: sender != 'ssabrii'
jobs:
 include:
  - stage: test
    script: true
  - stage: hello
    script: true

