language: android
jdk: oraclejdk8
dist: trusty
android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
