language: c
before_install:
 - wget https://dl.google.com/go/go1.13.linux-amd64.tar.gz
 - sudo tar -xvf go1.13.linux-amd64.tar.gz
 - export GOROOT=~/go
 - export PATH=$GOROOT/bin:$PATH
install: true
script: 
 - go version
 - go env

