language: node_js
node_js:
  - "8"
install: true
script: true
notifications:
  slack:
    rooms:
      secure: VveBRDGNTRxwb24fji9yhQX9DPvVIqDwBq8vG1fZShXYE6oMFOqK6/1MzX2m7/DkUZxPTwsZkaDLkMhll9PEAw7Tug5vi+j94eilBi0Lpa6kMb1xfK18vNoDEc/l9AKJWlUOtFctUndVzSNnJwmAzdvAOvf8OwsZaIhgSSWYD5FWfvtmy52ZH+FnOdHEm5f7T0HOjixqMOHpoFmKZ2fnWKdZor7VKqI2TwIWAmacje7PzpvUnZCis+PG6ygxo58DlkoqGK1L0G0H6APrS0lwyMsBACwbwXOR9NXhBHSveGoIf88ZSno5sifaEss9Ia/b30nKsDSMiAjMbo51MU7caFB8weOilw7rNmXhcT7eiMM9bzZzjD0euAoKjOQfiwdjYp1/VT70cXSPrUO/rtJfntjC9zHaksFYsLUleUfBGtcveEIiwk5eQ6UUdg7TUEWcfsY7o0I1J0O+wR1KD3Q74nInDO3dtjIBDPchSUBpSiyCiOfcP6UQB8WqL2zJ318ErG8414ekzyZ6jgm5WBorKwQw5m0cBp8nepW4WfBoRVgqtvp+M4S0a57vVTNE7yVt+65BCRsnx0eUUysBUmyb72+ndXx7uYTidE0R7hYT2GHbwGcZUFrBvWoYO61774FarVgiQuYgFnWV24hNsXFVl0dZ8RStePj5e86qFc5q/xw=
deploy:
  provider: releases
  api_key:
    secure: Z4dDbcbHM/Pbbou1MwabSrU3bb5dag5JnJd6Lme5FcfR+MNCi2+FCN9l3pz8R9/2Fi1BNAhkMKMwlF7YYoCYg1asoBQ8IQ9HZxXArFC0+7lUGEfWBC61hB4YkBchRvlhIWCkQo/hSsHPQfInZqjPrVf765c42YnAAgNMZq6GeIp4OmyeKnbUoOw6YzzLsFUSH4IgrvCI1LoHmz5Wy1812O3etkYCVf5dIG2AsJDBGNOeHWpxAGVmJ62nXt84UCQ0o3aNUS46wo28irV96ll/W/SME0Inw8jaz+ofsrFIs7C7eGmSYwyUqr/sweGGSWqUmc37P15/I0xdUFsX6trW4AxkGd+qfx9l8oBp7tFUaTn/hnoaAvbPLKHlOcSdBe9g+SRyzy8fyLxV4Ud1LqIirETj5yH5WZjNInQTXIsmemBNGCVQ9Fn54uszswZKdj62auG44Ex5WCMO4uXlDgjxEYajYrZH9LnmCSdTT73DqdPbzQxn7T5DmmzQbeiFFwYwnZYvdYOdhEaNS3mWRzXLKIKah6QC8HYSo15XY7dQqx3NG2iAz7JyYI2Q/iId3suiPDMUuFhdFvZt2IhTwPjDV23KN1lTABXxXxJyt62fhx5Of9WR+zV5FPWONbpH7YkY8EoHxw1L3mp84PamOfVvlo68+TR/MsdYAUrmgkmNnu8=
  file: ''
  run: echo 'hello world'
  on:
    repo: ssabrii/test
