dist: trusty
language: minimal
before_install:
 - sudo dpkg --purge packages-microsoft-prod && sudo dpkg -i packages-microsoft-prod.deb
 - sudo apt-get update
 - sudo apt-get install dotnet-sdk-2.1

install: true
script: skip
 
