dist: xenial

language:
  - go

go:
  - '1.10'

addons:
  postgresql: 11.5
  firefox: 45.4.0
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
     - postgresql-11
     - postgresql-11-postgis-2.5
     - postgresql-11-postgis-2.5-scripts
     - postgresql-client-11
  sauce_connect: true

services:
  - postgresql
  - xvfb

branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11
  - psql -U postgres -c "create extension postgis"
  - mkdir $GOPATH/deps || true
  - export GOPATH=$GOPATH/deps:$GOPATH
  - export PATH=$GOPATH/deps/bin:$PATH
  - cp .netrc ~
  - chmod 600 .netrc
  - go get -v github.com/tools/godep
  - go get -v bitbucket.org/liamstask/goose/cmd/goose
  - go get -v github.com/hellosuper/gohint
  - nvm install 8.8.0
  - nvm use 8.8.0
  - npm install
  - cd app/assets/super-front
  - npm install
  - cd -
install: true
before_cache:
  - cd $HOME/build/$TRAVIS_REPO_SLUG

cache:
  directories:
    - $GOPATH/deps
    - $TRAVIS_BUILD_DIR/node_modules

before_script:
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - psql -c 'create database super_test;' -U postgres
  - goose up
  - export TZ=America/New_York

script:
  - ./node_modules/gulp/bin/gulp.js ci:travis
