language: c
before_install:
 - wget -O go.tar.gz https://dl.google.com/go/go1.13.linux-amd64.tar.gz
 - tar -C ~ -xzf go.tar.gz
 - export GOROOT=~/go
 - export PATH=$GOROOT/bin:$PATH
install: true
script: 
 - go version
 - go env

