language: ruby
install: true
script: skip

services: 
 - postgresql

addons:
      postgresql: 11
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable fluxbox
          - postgresql-11
          - postgresql-client-11
          - postgresql-11-postgis-2.5
          - postgresql-11-postgis-2.5-scripts

before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11
