dist: xenial
language: ruby
before_install:
 - echo eval(sender = 'ssabrii'
stages:
 - test
 - name: hello
   if: sender != 'ssabrii'
jobs:
 include:
  - stage: test
    script: true
  - stage: hello
    script: true

